import "~/styles/globals.css";
import 'bootstrap-icons/font/bootstrap-icons.min.css'

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import NavigationBar from "./components/navigation";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Courtyard of Truth Minitries",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
// `${GeistSans.variable}`

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`bg-seance-950 text-seance-300 ${GeistSans.variable}`}>
      <body>
        <NavigationBar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
