import "~/styles/globals.css";
import 'bootstrap-icons/font/bootstrap-icons.min.css'

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import NavigationBar from "./components/navigation";
import Footer from "./components/footer";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Courtyard of Truth Minitries",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
// `${GeistSans.variable}`

export default function RootLayout({
  children,
  modal
}: Readonly<{ 
  children: React.ReactNode,
  modal: React.ReactNode 
}>) {
  return (
    <html lang="en" className={`bg-seance-950 text-seance-300 ${GeistSans.variable}`}>
      <body>
        <NavigationBar />
          {modal}
          {children}
          <Toaster position="top-right" />
        <Footer />
      </body>
    </html>
  );
}
